services:
  postgres:
    image: postgres
    ports:
      - 9053:5432
    environment:
      POSTGRES_DB: 'myDataBase'
      POSTGRES_USER: 'noteDB'
      POSTGRES_PASSWORD: 'noteDB'
      TZ: Asia/Yekaterinburg
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=asd@asd.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 9052:80

  backend:
    image: ruzinde/notes-api
    environment:
      - ConnectionStrings__default=Host=postgres;Database=myDataBase;Username=noteDB;Password=noteDB;
    ports:
      - 9051:8080

  frontend:
    image: ruzinde/notes:latest
    ports:
      - 9050:5173
volumes:
  postgres-data:
